apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels: 
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container-name
        image: "raiyanx/github-bugtracker"
        ports:
          - name: django-pod-port
            containerPort: 3000
            protocol: TCP