# Generated by Django 4.2.4 on 2023-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='collaborators',
            field=models.ManyToManyField(to='gb_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='repos',
            field=models.ManyToManyField(to='gb_app.repo'),
        ),
    ]
