# Generated by Django 4.2.4 on 2023-09-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0003_rename_repo_project_rename_repos_user_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
