# Generated by Django 4.2.4 on 2023-09-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0008_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='own_project',
            field=models.BooleanField(default=True),
        ),
    ]
