# Generated by Django 4.2.4 on 2023-09-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app', '0009_alter_project_own_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='own_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner_email',
        ),
    ]
