apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  labels: 
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: ui-container-name
        image: "raiyanx/github-bugtracker"
        ports:
          - name: ui-pod-port
            containerPort: 3000
            protocol: TCP