apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: postgres
  labels: 
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db-container-name
          image: "postgres"
          ports:
            - containerPort: 8000
              name: db-port
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_db
          volumeMounts:
            - name: pgvolume
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: pgvolume
          hostPath:
            path: "/pgdata"
            type: Directory